### ISSUE TITLE
Support PATCH extension? 

### ISSUE THREAD

**Issue by xiaoyao1991** [yahoo/elide-js#31]
Since [elide](https://github.com/yahoo/elide-js/) supports PATCH extension requests, shall we support PATCH extension in elide-js as well?

**Comment by clayreimann** [comment]
Patch extension is supported already. Checkout [`jsonapidatastore#commit`](https://github.com/yahoo/elide-js/blob/master/lib/datastores/jsonapidatastore.js#L1212)

**Comment by xiaoyao1991** [comment]
Can you provide some examples of how to make PATCH extension requests?

**Comment by clayreimann** [comment]
You should checkout the [tests](https://github.com/yahoo/elide-js/blob/master/spec/stores/jsonapidatastore.spec.js#L490-L601). It's pretty complicated and if you have suggestions on how it could be improved I'm all ears.
