### ISSUE TITLE
How to decide store type?

### ISSUE THREAD

**Issue by xiaoyao1991** [yahoo/elide-js#32]
Are there any guidelines on which store type(memory or jsonapi) to use for a specific model when defining schemas?

**Comment by clayreimann** [comment]
So you want to use a memory store when you want to cache the object locally (though admittedly the memory store is pretty half baked). The jsonapi store does no object level caching, so when you say `find('foo', 1)` it will always go to the API whereas the memory store could return the previously fetched response.
